### ISSUE TITLE
The REV Issuance page on the developer site needs updating to remove confusing statements

### ISSUE THREAD

**Issue by MaximilianR** [rchain/www#125]
Most of the page can very easily be fixed by for instance changing a word from "will" to "was".

For instance, this section in the top paragraph

> At the launch of main net, planned for February 4, 2020, there will be an issuance of REV at a 1:1 ratio based on a holder’s RHOC balance. REV will be the currency of the RChain blockchain. Among other things, REV will allow you to bond a validator’s stake, pay transaction fees, and deploy smart contracts on the new RChain blockchain. If you’re interested in building your own RChain-based dApp, you will need to acquire REV in order to do so.

could be rephrased to

> At the launch of main net, which occured February 25th, 2020, there was an issuance of REV at a 1:1 ratio based on a holder’s RHOC balance. REV is the currency of the RChain blockchain. Among other things, REV allows you to bond a validator’s stake, pay transaction fees, and deploy smart contracts on the new RChain blockchain. If you’re interested in building your own RChain-based dApp, you will need to acquire REV in order to do so.

Certain entries in the FAQ-box needs updating in a similar way. The Key Milestones-box should be updated with the accurate main net launch date as well.

**Comment by ian-bloom** [comment]
@JamesMoc Nice job on #128 , however we need to clear a few things up before publishing.
E.g.
> All RHOC tokens were converted at 1:1 ratio to REV tokens at the launch of the RChain main net (Mercury) on 25 Feb 2020 ~~at block height 9371743 on the Etherium Blockchain~~.

On Jan-28-2020 At Ethereum block 9371743 a "snapshot" was taken of all RHOC balances.

Maybe we should explain the *swap* more chronologically..

### What is RHOC ?
In 2017, the RChain Cooperative created RHOC tokens and sponsored a private sale.
  - **RHOC** is an Ethereum ERC20 token that lives on the Ethereum Blockchain. The native Ethereum token is the ETH.

### What is REV ?
At the launch of the RChain main net on February 25, 2020, there was an issuance of REV at a 1:1 ratio based on a holder’s RHOC balance.
  - **REV** is the native token of the RChain Blockchain. It is used to  bond a validator’s stake on RChain’s CBC Casper proof-of-stake consensus system, pay transaction fees, and deploy smart contracts on the new RChain blockchain. If you’re interested in building your own RChain-based dApp, you will need to acquire REV in order to do so.

### How can I check my REV balance?
REV exists only on the RChain Blockchain...
(list of 3rd party RChain Wallets + disclaimer)

### How was the *issuance* implemented
  - explanation of the *snapshot* and *freeze*
On Jan-28-2020 At Ethereum block 9371743 a "snapshot" was taken of all RHOC balances...
.. link to wallets.txt 
.. Exchanges were requested to halt trading during the freeze
  - How RHOC addresses and REV addresses related
    - Your RHOC is an ERC20 balance at a particular Ethereum address to which you hold the private key. REV addresses are derived from your Ethereum address so that your Ethereum private key will work with your REV.
